services:
  backend:
    image: home5a_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: home5a_backend
    restart: no
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - E:/Slava/kwork/1:/app/photos
      # - ./photos:/app/photos
    environment:
      - PHOTOS_PATH=/app/photos
    working_dir: /app/app

  frontend:
    image: home5a_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: home5a_frontend
    restart: no
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
    working_dir: /app
